### ISSUE TITLE
Perl support (bindings)

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-general#1]

**Comment by melo** [comment]
I believe this is solved with https://metacpan.org/release/Net-NATS-Client, right?

**Comment by ColinSullivan1** [comment]
At this point we haven't had much inbound interest so won't support an official perl binding, but we're happy to direct users to some contributions in the ecosystem.

Some NATS perl bindings include:
 * http://blogs.perl.org/users/sergey_kolychev/2017/11/perl-client-for-nats-streaming-messaging-system.html
 * https://github.com/carwynmoore/perl-nats
