### ISSUE TITLE
Request: restore commit history of go-nats repo to repair submodule commit references

### ISSUE THREAD

**Issue by emalm** [nats-io/nats-general#22]
Several projects in [Cloud Foundry](https://github.com/cloudfoundry) use NATS as a message bus, and in particular use the Golang client library to connect to a NATS cluster, often referring to the client code via a Git submodule. At some point, the client library was located at this repo address (https://github.com/nats-io/nats), and then later moved to https://github.com/nats-io/go-nats. Now that new repo content has been pushed to github.com/nats-io/nats, the GitHub redirects to those client-library commits no longer work.

Unfortunately, the failure of these redirects means that those submodule references are broken. For example, the submodule reference to https://github.com/nats-io/nats/tree/c0ad3f079763c06c3ce94ad12fa3f17e78966d99 in https://github.com/cloudfoundry/diego-release/tree/v1.0.0/src/github.com/nats-io returns a 404 on GitHub, and accordingly `git` chokes when initializing the submodule:

```
error: Server does not allow request for unadvertised object c0ad3f079763c06c3ce94ad12fa3f17e78966d99
Fetched in submodule path 'src/github.com/nats-io/nats', but it did not contain c0ad3f079763c06c3ce94ad12fa3f17e78966d99. Direct fetching of that commit failed.
```

Would you be able to push a historical copy of the https://github.com/nats-io/go-nats master branch tree to an orphaned branch on https://github.com/nats-io/nats to repair those submodule references to its commits?

Thanks very much,
Eric Malm, CF Diego Product Manager

/cc @jvshahid @nkaviani

**Comment by ColinSullivan1** [comment]
@emalm , This was caused by a recent repo rename to "nats".  We shuffled some names around to fix the repo redirect.  I apologize for your inconvenience, and thank you for raising this issue.  Can you give it a try now?

btw, you may want to look into golang vendoring - it works great to protect your go applications/packages from these types of changes and helps ensure repeatable builds.

Thanks,
Colin

**Comment by emalm** [comment]
Thanks for the quick fix, @ColinSullivan1 ! The https://github.com/nats-io/nats/tree/c0ad3f079763c06c3ce94ad12fa3f17e78966d99 link now resolves to the expected commit, and `git` also clones and checks out the commit correctly.

The Golang projects in CF have been gradually adopting various vendoring strategies now that tools such as `dep` and the forthcoming vgo have emerged with broad support in the Golang community, but we can't fix past tagged commits that still use submodules.

Thanks again,
Eric

**Comment by ColinSullivan1** [comment]
Anytime - Glad to hear it's fixed!
