### ISSUE TITLE
Feature Request:  Dart client for NATS

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-general#24]
We've had a few requests for official Dart clients.  There are no near term plans at the moment, but here is a place for requests, to express interest, and even implementation suggestions from the community.   Comments and requests on issues like these do inform our roadmap.

Some reasons why to implement:
* Use the [Flutter](https://flutter.io/ ) framework (https://flutter.io)  to deploy for Mobile, Desktop and Web.
* Reuse of code and types with different clients (mobile, desktop, web).
* Flutter Mobile is fast and easy and runs on Android and IOS
* Flutter Desktop is identical code and runs on Mac, Linux and Windows.
* Code reuse is 100% across Mobile and Desktop
* Flutter Web is under development by google. They have skia cross compiling to WASM for browsers, and Flutter code will run on top.

Hat tip to Gerard Webb for the list.

We are happy to help guide implementation for contributions in this area.

Existing NATS client:
https://github.com/kranfix/dart-nats-protocol

Additional References:
https://github.com/nats-io/gnatsd/issues/315#issuecomment-260348248
https://groups.google.com/forum/#!topic/natsio/tj9MMLLmyhw
https://pub.dartlang.org/packages/nuid

**Comment by munukutla** [comment]
Started working on it. Preliminary pub-sub now works. Should add clustering support. https://github.com/munukutla/nats-dart

**Comment by ColinSullivan1** [comment]
Closing this as there are now a few choices for Dart clients in the NATS ecosystem.  Thank you for the contributions!

**Comment by kingquant-com** [comment]
Flutter Web official release version is coming. Right now there is no nats client supporting Flutter Web. There are several clients to support flutter desktop+app, but not web.

Is there any official plan to make a Dart/Flutter client? One nats.dart rules it all (desktop, app, web)! 

Thanks

**Comment by NicolasCaous** [comment]
@ColinSullivan1 please consider reopening

**Comment by neeraj-htp** [comment]
> 

@ColinSullivan1 can you please list out the Dart clients options here?
- https://github.com/munukutla/nats-dart is not stable yet as its own `readme` says this.
- https://pub.dev/packages/dart_nats does not support a lot of features like NATS Auth, auto-reconnection, NATS 2.2, etc.
Considering the growth of Flutter in the mobile app domain, a stable dart/flutter client is the requirement of the hour.
