### ISSUE TITLE
Support web/mobile clients over Internet

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-general#4]
NATS needs a secure, highly scalable mechanism to allow clients using mobile devices and/or web browsers to connect via the internet(s). 

Because this feature may span multiple NATS components, this issue will be a meta-placeholder for discussion.

**Comment by ColinSullivan1** [comment]
This will be addressed as websocket connections on the [roadmap](https://nats.io/about/#roadmap).   Most of our clients are lightweight enough to operate on mobile devices, and the [nats.ts](https://github.com/nats-io/nats.ts) and [nats.js](https://github.com/nats-io/nats.js) will be particularly ideal.

There is also an excellent REST proxy into NATS, [resgate.io](http://resgate.io).
