### ISSUE TITLE
NATS Maintainer Vote - Matthias Hanel

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats-general#52]
NATS Maintainers - 

@matthiashanel is being nominated by @ColinSullivan1 to be a Maintainer for the NATS Organization.

Matthias demonstrates a commitment to the NATS project with a substantial number of commits to the NATS server. He's been instrumental in project initiatives involving account management, tooling, and security, and regularly helps NATS users on the NATS Slack channel. Matthias will be working on tooling, various clients, and the NATS server.

As per [NATS Governance](https://github.com/nats-io/nats-general/blob/master/GOVERNANCE.md), Maintainers are required to approve Matthias as a NATS Maintainer. 

Please comment with your desired vote (Y) = Yes, (N) = No, or (A) = Abstain, by **Thursday, December 10, 2020**. 

Thank you for your participation!

Maintainer vote required:
@derekcollison @ColinSullivan1 @wallyqs @ripienaar @variadico @davidkemper @sasbury @kozlovic @aricart @levb @pires @mmmries @brianshannan @charliestrawn @olegshaldybin @gcolliso @watfordgnf

**Comment by ripienaar** [comment]
Y

**Comment by kozlovic** [comment]
Y

**Comment by wallyqs** [comment]
Y

**Comment by watfordgnf** [comment]
Y

**Comment by derekcollison** [comment]
Y

**Comment by derekcollison** [comment]
Approve

**Comment by derekcollison** [comment]
Y

**Comment by ColinSullivan1** [comment]
Y (binding)

**Comment by mmmries** [comment]
Y

**Comment by gcolliso** [comment]
Y

**Comment by aricart** [comment]
Y

**Comment by olegshaldybin** [comment]
Y

**Comment by sasbury** [comment]
Y

**Comment by variadico** [comment]
Y

**Comment by pires** [comment]
Y

**Comment by levb** [comment]
Y

**Comment by charliestrawn** [comment]
Y

**Comment by gcolliso** [comment]
Thank you NATS Maintainers for participating in this maintainer nomination.

Congratulations, @matthiashanel you have been approved as a NATS Maintainer!

**Comment by matthiashanel** [comment]
Thanks everyone!
