### ISSUE TITLE
Are you a NATS.io user?

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-general#57]
# Are you using NATS.io?

If you are looking at or using NATS, thank you!  

It is users like you in the OSS community and ecosystem that help make projects like NATS successful.  We love to hear from our users, learn about how you are using NATS, and discover what we could add or improve to make NATS better for you!

## Interested in sharing your experience?

If you would like to share here, we'd love to see a comment answering any of the following questions.

```text
Company/Project Name:

Website:

How did you hear about NATS?

How are you using NATS?  

Do you have any feature requests?

What would you change about NATS?

Are you running NATS in production?

Any other comments?
```

Alternatively, feel free to email us at info@nats.io, or join our [slack organization](https://slack.nats.io).

To request new features or enhancements don’t hesitate to add a request at [nats-general/issues](https://github.com/nats-io/nats-general/issues/new/choose) or any of our other repositories.

**Comment by ColinSullivan1** [comment]
**Company name:**  [Synadia](https://synadia.com)

**How did you hear about NATS?**
Our CEO, Derek Collison created NATS.

**What are you using NATS for?**
To provide secure global connectivity for applications, devices, and endpoints and to democratize access to streams and services across the world.

**Do you have any feature requests?**
Something around schema management would be great!

**What would you change about NATS?**
As we come up with ideas we’ll open issues or PRs.

**Are you running NATS in production?**
Yes, for three years now.  We are happy to be a part of the NATS community and contribute to the NATS.io project.

**Comment by gcolliso** [comment]
Moved to DIscussions
