### ISSUE TITLE
NATS Maintainer Vote -  Scott Fauerbach

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats-general#61]
NATS Maintainers -

@scottf is being nominated by @ColinSullivan1 to be a Maintainer for the NATS Organization.

Scott has demonstrated a commitment to the NATS project with a substantial number of commits to the NATS Java and .NET clients. In addition, he's provided numerous example blogs & videos to help the community and regularly assists NATS users on the NATS Slack channel. Scott will be continuing to evangelize NATS in the Java ecosystem, various client development and future integration points with NATS.

As per [NATS Governance](https://github.com/nats-io/nats-general/blob/master/GOVERNANCE.md), Maintainers are required to approve Scott as a NATS Maintainer. 

Please comment with your desired vote (Y) = Yes, (N) = No, or (A) = Abstain, by Wednesday, September 8, 2021. 

Thank you for your participation!

Maintainer vote required:
@derekcollison @ColinSullivan1 @wallyqs @ripienaar @variadico @davidkemper @sasbury @kozlovic @aricart @levb @pires @mmmries @brianshannan @charliestrawn @olegshaldybin @gcolliso @watfordgnf @matthiashanel

**Comment by aricart** [comment]
Y

**Comment by kozlovic** [comment]
Y

**Comment by gcolliso** [comment]
Y

**Comment by ripienaar** [comment]
Y

**Comment by charliestrawn** [comment]
Y

**Comment by derekcollison** [comment]
Y

**Comment by matthiashanel** [comment]
Y

**Comment by mmmries** [comment]
Y

**Comment by aricart** [comment]
Lgtm.

**Comment by wallyqs** [comment]
Y

**Comment by pires** [comment]
Y

**Comment by levb** [comment]
y

**Comment by davidkemper** [comment]
Y

**Comment by variadico** [comment]
Y

**Comment by gcolliso** [comment]
14 - Y
4 - no response

Thank you NATS Maintainers for participating in this maintainer nomination.

Congratulations, @scottf you have been approved as a NATS Maintainer!

**Comment by ColinSullivan1** [comment]
Y
