### ISSUE TITLE
Feature Request: Minimal Distributed Cache

### ISSUE THREAD

**Issue by jeffreywstevens** [nats-io/nats-general#87]
It would be nice if I didn't have to stand up Redis or NCache once things scale up and out.  So Key Value or Object Store with an expiration would make it a winner. Redis has many similar features. The fact you can be installed on Windows makes Nats more flexible.

**Comment by jnmoyne** [comment]
You can already do size or TTL expiration with the KV and use it as a cache but JetStream is a data store with expiration, not a cache with LRU eviction.

**Comment by jeffreywstevens** [comment]
Nice. I must have missed that with the Key Vault. I firmly explored TTL on the streams. I just need to circle back  I can handle the lack of LRU and sliding expiration. I have to be on Windows for this app so maybe I can ditch NCache or the SQL backing C# distributed cache. Less dependencies will help me.

**Comment by jeffreywstevens** [comment]
I missed this with the Key Vault because I thought expiration wasn't working. The reason is I was just looking at the sequence number returned by the PUT.  
- If the key expires, and you perform another PUT on the same key, the sequence will still increment by 1 from the last PUT.
- If you delete the key, then perform a PUT, the sequence starts at 1 again.
I am not sure if I like that behavior, but I now know it.

**Comment by jeffreywstevens** [comment]
Actually, it won't work.  Your TTL is at a bucket level. Most cache interfaces allow TTL at the key put,set level.

**Comment by ripienaar** [comment]
The sequence does not return to one after a delete. Only after the entire bucket is destroyed. It’s a bucket sequence not key sequence.

**Comment by jeffreywstevens** [comment]
Thanks for that. I was only using one key.

**Comment by jeffreywstevens** [comment]
I tried to write a Nats implementation of the C# IDistributedCache. Back to the original options.  Thanks everyone for the help!

**Comment by jnmoyne** [comment]
IMHO rare are the caching use cases that need per entry TTL and you can always use more than one bucket each with its own TTL.

**Comment by jeffreywstevens** [comment]
Good point. However, in my experience, it depends on the stored entity and its volatility. The bucket per entity may solve that. However, I usually prefer just one cache/bucket and an excellent key strategy.  Thanks for the input. I will keep working on this. Nats will still be my connective tissue for decoupling my app.
