### ISSUE TITLE
NATS Maintainer Vote - Byron Ruth

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats-general#90]
NATS Maintainers -

[Byron Ruth](https://github.com/bruth) is being nominated by @wallyqs to be a Maintainer for the NATS Organization.

Byron has been a long-time NATS user and his contributions in the areas of documentation, release management, and client development have been fundamental in improving the project.

As per [NATS Governance](https://github.com/nats-io/nats-general/blob/master/GOVERNANCE.md), nominee approval is required by a majority vote by current Maintainers.

Please comment with your desired vote (Y) = Yes, (N) = No, or (A) = Abstain, by Wednesday, July 26, 2023.

Thank you for your participation!

Maintainer vote required:
@derekcollison @ColinSullivan1 @wallyqs @ripienaar @davidkemper @sasbury @kozlovic @aricart @levb @pires @mmmries @brianshannan @charliestrawn @olegshaldybin @gcolliso @watfordgnf @matthiashanel @scottf @philpennock @Jarema @neilalexander

**Comment by derekcollison** [comment]
Yes

**Comment by neilalexander** [comment]
Yes

**Comment by gcolliso** [comment]
Y

**Comment by scottf** [comment]
Yes

**Comment by aricart** [comment]
Yes

**Comment by sasbury** [comment]
yes

**Comment by ripienaar** [comment]
Yes

**Comment by Jarema** [comment]
Yes

**Comment by kozlovic** [comment]
Y

**Comment by matthiashanel** [comment]
Y

**Comment by aricart** [comment]
Y

**Comment by philpennock** [comment]
yes

**Comment by ColinSullivan1** [comment]
Y

**Comment by mmmries** [comment]
Y

**Comment by gcolliso** [comment]
Response for Byron Ruth Maintainer vote -
14 - Yes
7 - no response

Thank you NATS Maintainers for participating in this maintainer nomination.

:tada: Congratulations, @bruth you have been approved as a NATS Maintainer!

**Comment by bruth** [comment]
🙌 Thank you all!
