### ISSUE TITLE
NATS Maintainer Vote - Piotr Piotrowski

### ISSUE THREAD

**Issue by gcolliso** [nats-io/nats-general#93]
NATS Maintainers -

[Piotr Piotrowski](https://github.com/piotrpio) is being nominated by [Tomasz Pietrek](https://github.com/Jarema) to be a Maintainer for the NATS Organization.

For over a year, Piotr has been actively contributing to various repositories in the NATS ecosystem and is a most active Go client contributor. He is also responsible for the nats.go client releases since September 2022.

As per [NATS Governance](https://github.com/nats-io/nats-general/blob/master/GOVERNANCE.md), nominee approval is required by a majority vote by current Maintainers.

Please comment with your desired vote (Y) = Yes, (N) = No, or (A) = Abstain, by **Wednesday, October 18, 2023**.

Thank you for your participation!

Maintainer vote required:
@derekcollison @ColinSullivan1 @wallyqs @ripienaar @davidkemper @sasbury @kozlovic @aricart @levb @pires @mmmries @brianshannan @charliestrawn @olegshaldybin @gcolliso @watfordgnf @matthiashanel @scottf @philpennock @Jarema @neilalexander @bruth

**Comment by gcolliso** [comment]
Y

**Comment by kozlovic** [comment]
Y

**Comment by bruth** [comment]
Y

**Comment by ripienaar** [comment]
y

**Comment by pires** [comment]
Y

**Comment by derekcollison** [comment]
Y

**Comment by Jarema** [comment]
Y

**Comment by scottf** [comment]
Y

**Comment by levb** [comment]
Y

**Comment by sasbury** [comment]
Y

**Comment by aricart** [comment]
Y

**Comment by scottf** [comment]
Y

**Comment by sasbury** [comment]
Y- StephenOn Oct 19, 2023, at 9:19 AM, Scott Fauerbach ***@***.***> wrote:﻿
Y

**Comment by matthiashanel** [comment]
Y

**Comment by neilalexander** [comment]
Y

**Comment by gcolliso** [comment]
Response for Piotr Piotrowski Maintainer vote -
15 - Yes
7 - no response

Thank you NATS Maintainers for participating in this maintainer nomination.

🎉 Congratulations, @piotrpio you have been approved as a NATS Maintainer!

**Comment by piotrpio** [comment]
Thank you all!
